<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e0421c83-b988-4a99-b612-e2449652f6e9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\Commands\**" />
    <Compile Remove="Application\Handlers\**" />
    <Compile Remove="Application\Queries\**" />
    <Compile Remove="Infrastructure\Services\**" />
    <Compile Remove="Presentation\Controllers\**" />
    <Content Remove="Application\Commands\**" />
    <Content Remove="Application\Handlers\**" />
    <Content Remove="Application\Queries\**" />
    <Content Remove="Infrastructure\Services\**" />
    <Content Remove="Presentation\Controllers\**" />
    <EmbeddedResource Remove="Application\Commands\**" />
    <EmbeddedResource Remove="Application\Handlers\**" />
    <EmbeddedResource Remove="Application\Queries\**" />
    <EmbeddedResource Remove="Infrastructure\Services\**" />
    <EmbeddedResource Remove="Presentation\Controllers\**" />
    <None Remove="Application\Commands\**" />
    <None Remove="Application\Handlers\**" />
    <None Remove="Application\Queries\**" />
    <None Remove="Infrastructure\Services\**" />
    <None Remove="Presentation\Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\NicolasQuiPaieData\NicolasQuiPaieData.csproj" />
    <ProjectReference Include="..\NicolasQuiPaieAPI.Infrastructure\NicolasQuiPaieAPI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
