global using FluentValidation;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi;
global using NicolasQuiPaieAPI.Application.Interfaces;
global using NicolasQuiPaieAPI.Application.Mappings;
global using NicolasQuiPaieAPI.Application.Services;
global using NicolasQuiPaieAPI.Application.Validators;
global using NicolasQuiPaieAPI.Extensions;
global using NicolasQuiPaieAPI.Infrastructure.Data;
global using NicolasQuiPaieAPI.Infrastructure.Models;
global using NicolasQuiPaieAPI.Infrastructure.Repositories;
global using NicolasQuiPaieAPI.Presentation.Endpoints;
global using NicolasQuiPaieData.DTOs;
global using Serilog;
global using Serilog.Sinks.MSSqlServer;
global using System.Data;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using ProposalStatus = NicolasQuiPaieAPI.Infrastructure.Models.ProposalStatus;
global using VoteType = NicolasQuiPaieAPI.Infrastructure.Models.VoteType;